name: n
description: "Anonymous Social App"

publish_to: 'none'
version: 1.0.0+1

environment:
  #sdk: ^3.6.1
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  path_provider: ^2.1.5
  # recorder: ^0.4.1
  record: ^5.2.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.5

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
